name: Update application on remote server
on: [push]
jobs:
  update:
    name: Update Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Copy script to remote server
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: '.github/scripts/update_app.sh'
          target: '/home/${{ secrets.SERVER_USERNAME }}/update_app.sh'

      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            chmod +x /home/${{ secrets.SERVER_USERNAME }}/update_app.sh
            /home/${{ secrets.SERVER_USERNAME }}/update_app.sh \
                timeseries_viewer \
                /home/${{ secrets.SERVER_USERNAME }}/apps/timeseries_viewer \
                www-data \
                /var/opt/static \
                /var/opt/workspaces/
            # Delete the script after execution
            rm /home/${{ secrets.SERVER_USERNAME }}/update_app.sh
