name: Update application on remote server
on: [push]

jobs:
  update:
    name: Update Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Copy script to remote server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          strip_components: 2
          source: '.github/scripts/update_app.sh'
          target: '/home/${{ secrets.SERVER_USERNAME }}/'

      - name: Updating Application
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_NAME: 'timeseries_viewer'
          APP_PATH: '/home/${{ secrets.SERVER_USERNAME }}/apps/timeseries_viewer'
          NGINX_USER: 'www-data'
          STATIC_FILES_PATH: '/var/opt/static'
          WORKSPACES_PATH: '/var/opt/workspaces'
          CONDA_EXECUTABLE: '/home/${{ secrets.SERVER_USERNAME }}/miniconda3/bin/conda'
          APP_STATIC_FILES_PATH: '/home/${{ secrets.SERVER_USERNAME }}/apps/timeseries_viewer/tethysapp/timeseries_viewer/public'
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          envs: APP_NAME,APP_PATH,NGINX_USER,STATIC_FILES_PATH,WORKSPACES_PATH,CONDA_EXECUTABLE,APP_STATIC_FILES_PATH
          script: |
            echo "APP_NAME=$APP_NAME"
            echo "APP_PATH=$APP_PATH"
            echo "NGINX_USER=$NGINX_USER"
            echo "STATIC_FILES_PATH=$STATIC_FILES_PATH"
            echo "WORKSPACES_PATH=$WORKSPACES_PATH"
            echo "CONDA_EXECUTABLE=$CONDA_EXECUTABLE"
            echo "APP_STATIC_FILES_PATH=$APP_STATIC_FILES_PATH"
            chmod +x $HOME/update_app.sh

            $HOME/update_app.sh \
                $APP_NAME \
                $APP_PATH \
                $NGINX_USER \
                $STATIC_FILES_PATH \
                $WORKSPACES_PATH \
                "none" \
                $CONDA_EXECUTABLE \
                $APP_STATIC_FILES_PATH \
                --skip-syncstores

      - name: Cleanup
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            rm $HOME/update_app.sh
